#!/usr/bin/env bash
# Capture the pre-change state of this Raspberry Pi.
#
# Read-only: copies config files into backup/ and writes a hardware report to
# docs/HARDWARE.md. Run this BEFORE Phase 1 touches anything, and again after
# any boot-config change so backup/ always holds a known-good rollback target.
#
# Safe to re-run: existing backups are kept, timestamped copies are added.

set -uo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKUP="$REPO/backup"
STAMP="$(date +%Y%m%d-%H%M%S)"
REPORT="$REPO/docs/HARDWARE.md"

mkdir -p "$BACKUP"

# ── 1. Back up the files Phase 1 and Phase 6b will modify ──────────────
# Keep a pristine ".orig" copy the first time we ever see each file, plus a
# timestamped copy on every run. The .orig is the true rollback target.
backup_file() {
    local src="$1" name
    name="$(basename "$src")"
    [ -e "$src" ] || { echo "  (absent) $src"; return; }
    [ -e "$BACKUP/$name.orig" ] || cp -a "$src" "$BACKUP/$name.orig"
    cp -a "$src" "$BACKUP/$name.$STAMP"
    echo "  saved   $src"
}

echo "Backing up config files:"
backup_file /boot/firmware/config.txt
backup_file /boot/firmware/cmdline.txt
backup_file "$HOME/.bash_profile"
backup_file "$HOME/.profile"
backup_file "$HOME/.bashrc"

# ── 2. Write the hardware/system report ────────────────────────────────
# Wrap each probe so a missing tool never aborts the capture.
# `sed -e '$a\'` appends a trailing newline when the source lacks one — several
# /proc/device-tree values are NUL-terminated with no newline, which would
# otherwise swallow the closing code fence onto the same line.
probe() {
    echo; echo "### $1"; echo '```'
    shift
    { "$@" 2>&1 || echo "(probe failed)"; } | sed -e '$a\'
    echo '```'
}

{
    echo "# Hardware & System Baseline"
    echo
    echo "Generated by \`scripts/baseline-capture.sh\` on $(date -Is)"
    echo
    echo "This is a **captured snapshot**, not hand-written documentation."
    echo "Re-run the script after any boot-config change to refresh it."

    probe "Board"              cat /proc/device-tree/model
    probe "OS"                 cat /etc/os-release
    probe "Kernel / arch"      uname -a
    probe "Memory"             free -h
    probe "Swap"               swapon --show
    probe "Disk"               df -h /
    probe "CPU temperature"    vcgencmd measure_temp
    probe "Throttle flags"     vcgencmd get_throttled
    probe "Network interfaces" ip -br addr

    echo
    echo "## Display"
    probe "Framebuffer devices" ls -la /dev/fb0 /dev/fb1
    probe "fb0 driver name"     cat /sys/class/graphics/fb0/name
    probe "fb0 geometry"        cat /sys/class/graphics/fb0/virtual_size
    probe "fb0 bit depth"       cat /sys/class/graphics/fb0/bits_per_pixel
    probe "fb0 stride"          cat /sys/class/graphics/fb0/stride
    probe "fbset"               fbset -s
    probe "DRI devices (GPU)"   ls -la /dev/dri
    probe "Backlight control"   ls -la /sys/class/backlight
    probe "SPI / I2C devices"   ls -la /dev/spidev10.0 /dev/i2c-1
    probe "Input devices"       cat /proc/bus/input/devices
    probe "Display modules"     sh -c "lsmod | grep -iE 'fbtft|ili|ads7846|spi|drm|vc4'"
    probe "boot config.txt"     cat /boot/firmware/config.txt
    probe "boot cmdline.txt"    cat /boot/firmware/cmdline.txt
    probe "LCD-show marker"     cat "$HOME/LCD-show/.have_installed"

    echo
    echo "## Runtime environment"
    probe "cgroup controllers"  cat /sys/fs/cgroup/cgroup.controllers
    probe "systemd version"     sh -c "systemctl --version | head -1"
    probe "systemd default"     systemctl get-default
    probe "user lingering"      ls -la /var/lib/systemd/linger/
    probe "user groups"         id
    probe "Python"              python3 --version
    probe "Toolchain on PATH"   sh -c "command -v git curl xz gcc g++ make node npm hermes codex claude || true"
    probe "PATH"                sh -c 'echo "$PATH"'
} > "$REPORT"

echo
echo "Wrote report: $REPORT"
echo "Backups in:   $BACKUP"
